remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: es-AR
title: "Rosario Budokan"
description: "Sede Rosario de la Asociación de Kendo & Iaido Shin Sen Kai"

logo: "/images/rbk_logo.png"

# Collections
collections:
  disciplinas:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Disciplinas defaults
  - scope:
      path: "_disciplinas"
      type: disciplinas
    values:
      layout: post
      comments: false
      share: true

# Site Author
author:
  name: Sebastián R. Vansteenkiste